upgrade nixpkgs to fix gcloud crash on MacOS 27 (#7600)
Deal with NixOS/nixpkgs#541367 on MacOS 27:

    $ gcloud --version
    Assertion failed: (trampoline_handle), function ffi_trampoline_table_alloc_block_invoke, file closures.c, line 258.
    Abort trap: 6

- update to NixOS/nixpkgs@f45c6f04c2f013f004bf94e284e95d72898d9393
  - NixOS/nixpkgs@b6c8664de9b6cc07fe5666a29f91884ba81197c4, the latest
    nixpkgs-unstable ref there at time of writing, is broken on
    aarch64-linux (firefox issue)
    
        error: output '/nix/store/9n53j9xnff4l259qm822a31qbh9qdzhb-firefox-157.0' is not allowed to refer to the following paths:
                 /nix/store/99zij8qfs8wzbb2njrj18ys8hpnrcj3p-gcc-wrapper-16.2.0
- remove #6102 workaround for helm-unittest
- use `stdenv.hostPlatform.is*` instead of `stdenv.is*`, avoiding
  warnings added in NixOS/nixpkgs#518407
- adapt to Firefox 156: new `userContext` field, scheme required
- solve npm warnings with new `allowScripts` field

scripts/nixpkgs-version-changes.sh output:

    system aarch64-darwin
    nixpkgs b3c092d3c36d91e2f61f3dfb39a159f180a56659 -> f45c6f04c2f013f004bf94e284e95d72898d9393
    auth0-cli: 1.31.0 -> 1.32.0
    circleci-cli: 0.1.38646 -> 1.0.48571
    curl: 8.20.0 -> 8.22.0
    deno: 2.8.3 -> 2.9.6
    docker: 29.5.3 -> 29.8.1
    gh: 2.95.0 -> 2.101.0
    git: 2.54.0 -> 2.55.0
    google-cloud-sdk: 570.0.0 -> 583.0.0
    grpcurl: 1.9.3 -> 1.9.4
    helm: 4.2.1 -> 4.3.0
    hub: - -> 2.14.2-unstable-2022-12-01
    hub-unstable: 2022-12-01 -> -
    istioctl: 1.30.1 -> 1.30.3
    jq: 1.8.1 -> 1.8.2
    k6: 2.0.0 -> 2.2.0
    kubectl: 1.36.2 -> 1.37.1
    nix: 2.34.7+1 -> 2.34.8
    nodejs: 24.15.0 -> 24.20.0
    postgresql: 14.23 -> 14.24
    pre-commit: 4.5.1 -> 4.6.2
    pulumi: 3.246.0 -> 3.261.0
    python3: 3.13.13 -> 3.14.7
    python3-aiohttp: 3.13.5 -> 3.14.3
    python3-colorlog: 6.10.1 -> 6.12.0
    python3-datadog: 0.52.1 -> 0.54.0
    python3-flask: 3.1.2 -> 3.1.3
    python3-gitpython: 3.1.50 -> 3.1.58
    python3-google-cloud-bigquery: 3.40.0 -> 3.41.0
    python3-google-cloud-storage: 3.10.1 -> 3.12.0
    python3-junit2html: 31.1.3 -> 31.1.4
    python3-pip: 25.3 -> 26.1.2
    python3-pulumi: 3.192.0 -> 3.263.0
    python3-pydantic: 2.12.5 -> 2.13.4
    python3-pyjwt: 2.12.1 -> 2.13.0
    python3-regex: 2026.4.4 -> 2026.7.11
    python3-requests: 2.33.1 -> 2.34.2
    python3-rich: 14.3.3 -> 15.0.0
    ripgrep: 15.1.0 -> 15.2.0
    rsync: 3.4.1 -> 3.5.0
    ruff: 0.15.17 -> 0.16.8
    sbt: 1.12.11 -> 2.0.9
    skopeo: 1.23.0 -> 1.24.1
    tmux: 3.6a -> 3.7c
    which: 2.23 -> 2.25
    xxd-tinyxxd: 1.3.15 -> 1.3.16

---------

Assisted-by: Copilot:gpt-6-astra
Assisted-by: Claude:claude-5.5-opus
Signed-off-by: Stephen Compall <stephen.compall@digitalasset.com>